language: python
python:
  - 3.4
before_install:
  - sudo apt-get install libjpeg8 libjpeg-dev libfreetype6 libfreetype6-dev zlib1g-dev
install:
  - pip install --no-index -f wheels/ -r requirements.txt
env: TRAVIS=TRAVIS
script: make ci_test
after_script:
  - coveralls
