language: python
python:
  - 3.4
before_install:
  - sudo apt-get install libtiff5-dev libjpeg8-dev zlib1g-dev \
    libfreetype6-dev liblcms2-dev libwebp-dev tcl8.6-dev tk8.6-dev python-tk
install:
  - pip install --no-index -f wheels/ -r requirements.txt
env: TRAVIS=TRAVIS
script: make ci_test
after_script:
  - coveralls
